import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Generated by globalSetup.ts at test-run time; not committed (see .gitignore).
export const TUNER_FIXTURE_PATH = path.resolve(__dirname, '../fixtures/synth/tuner-e4.wav')
export const SCALE_MISTAKE_FIXTURE_PATH = path.resolve(__dirname, '../fixtures/synth/scale-mistake.wav')
